<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'Скоро відкриття<br />
+38 093 7815767 || Abazherka@gmail.com
https://vk.com/abazherka<br />';
	public $display_offline_message = '1';
	public $offline_image = 'images/logo-abazherka.1.jpg';
	public $sitename = 'Abazherka';
	public $editor = 'jce';
	public $captcha = '0';
	public $list_limit = '20';
	public $access = '1';
	public $debug = '0';
	public $debug_lang = '0';
	public $dbtype = 'mysql';
	public $host = 'localhost';
	public $user = 'root';
	public $password = 'root';
	public $db = 'abazherka_old';
	public $dbprefix = 'm4ayl_';
	public $live_site = '';
	public $secret = '46ol7QSdMn1fPZQM';
	public $gzip = '0';
	public $error_reporting = 'none';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '127.0.0.1';
	public $ftp_port = '21';
	public $ftp_user = 'admin';
	public $ftp_pass = 'ilovekiril2009';
	public $ftp_root = '';
	public $ftp_enable = '0';
	public $offset = 'Europe/Kiev';
	public $mailer = 'mail';
	public $mailfrom = 'olegkulik91@gmail.com';
	public $fromname = 'yanaz';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '0';
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'localhost';
	public $smtpsecure = 'none';
	public $smtpport = '25';
	public $caching = '0';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $MetaDesc = '';
	public $MetaKeys = '';
	public $MetaTitle = '1';
	public $MetaAuthor = '1';
	public $MetaVersion = '0';
	public $robots = '';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $unicodeslugs = '1';
	public $feed_limit = '10';
	public $log_path = '/home/yanaz/www/www/logs';
	public $tmp_path = '/home/yanaz/www/www/tmp';
	public $lifetime = '160';
	public $session_handler = 'database';
	public $MetaRights = '';
	public $sitename_pagetitles = '0';
	public $force_ssl = '0';
	public $feed_email = 'author';
	public $cookie_domain = '';
	public $cookie_path = '';
}